#            _
#    _______| |__  _ __ ___
#   |_  / __| '_ \| '__/ __|
#  _ / /\__ \ | | | | | (__
# (_)___|___/_| |_|_|  \___|
# --------------------------------------------------------------------
# Amber's zsh configuration


# ------------------------------ hyfetch -----------------------------
# Start with hyfetch in Kitty windows (i.e., not VSCode)
# This makes the prompt jump when using p10k instant prompt. I don't mind
# because it's fast enough that if I know what I'm typing when I open the
# terminal I've only typed a character or two.
if [[ $TERM == "xterm-kitty" ]]; then
    hyfetch --ascii-file ~/.config/arch-dots-text \
        -p $(shuf -e -n 1 \
        transgender \
        nonbinary \
        demigirl \
        lesbian \
        progress \
        rainbow \
        bisexual \
        pansexual \
        old-polyam)
else
    :
fi
# --------------------------------------------------------------------


# ------------------- powerlevel10k instant prompt -------------------
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
# --------------------------------------------------------------------


# ----------------------- zsh (autogenerated) ------------------------
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/amber/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# --------------------------------------------------------------------


# ---------------------- zsh pywal integration -----------------------
# Import colorscheme from 'wal' asynchronously
# &   # Run the process in the background.
# ( ) # Hide shell job control messages.
# Not supported in the "fish" shell.
# (cat ~/.cache/wal/sequences &)

# Alternative (blocks terminal for 0-3ms)
# cat ~/.cache/wal/sequences

# To add support for TTYs this line can be optionally added.
source ~/.cache/wal/colors-tty.sh
# --------------------------------------------------------------------


# Enable syntax highlighting and autosuggestions
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# Bind Tab to accept next token of autosuggestion
# ! This is broken - probably the fzf tab keybinding? I'd like to have both on tab to be honest.
bindkey '\t' forward-word


# -------------------------- custom aliases --------------------------
# Change directory and list contents
cl() {
    cd $1 && ls -Al
}
# From the internet - search manpages for a term
fman() {
    man $1 | grep -irn $2 -
}
gits() {
    git status
}
gd() {
    git diff $@
}
# Gitmoji alias
gm() {
    gitmoji commit
}
# Commit alias
gc() {
    git commit $@
}
# --------------------------------------------------------------------


# Created by `pipx` on 2024-06-01 17:52:50
export PATH="$PATH:/home/amber/.local/bin"


# ------------------ powerlevel10k (autogenerated) -------------------
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
# --------------------------------------------------------------------


# Several following sections from "7 Amazing CLI Tools You Need To Try"
# Josean Martinez https://youtu.be/mmqDYw9C30I
# --------------------- fzf / fd and keybindings ---------------------
eval "$(fzf --zsh)"

show_file_or_dir_preview="if [ -d {} ]; then eza --tree --color=always {} | head -200; else bat -n --color=always --line-range :500 {}; fi"

# Replace fzf algorithm with fd
export FZF_DEFAULT_COMMAND="fd --hidden --strip-cwd-prefix --exclude .git"
export FZF_CTRL_T_COMMAND="--preview '$show_file_or_dir_preview'"
export FZF_ALT_C_COMMAND="--preview 'eza --tree --color=always {} | head -200'"

_fzf_compgen_path() {
    fd --hidden --exclude .git . "$1"
}

_fzf_compgen_dir() {
    fd --type=d --hidden --exclude .git . "$1"
}

# Advanced control depending on what command fzf is initiated for
_fzf_comprun() {
    local command=$1
    shift

    case "$command" in
        cd)             fzf --preview "eza --tree --color=always {} | head -200" "$@" ;;
        export|unset)   fzf --preview "eval 'echo \$' {}" "$@" ;;
        ssh)            fzf --preview "dig {}" "@" ;;
        *)              fzf --preview "--preview 'bat -n --color=always --line-range :500 {}'" "$@" ;;
    esac
}
# --------------------------------------------------------------------


# ------------------------- bat (better cat) -------------------------
export BAT_THEME="Catppuccin Macchiato"
# --------------------------------------------------------------------


# ---------------------------- fzf-git.sh ----------------------------
source ~/.scripts/fzf-git.sh
# --------------------------------------------------------------------


# ------------------------- eza (better ls) --------------------------
alias ls="eza --color=always --long --git --no-filesize --icons=always --no-time --no-user --no-permissions"
# --------------------------------------------------------------------


# ----------------------------- thefuck ------------------------------
eval $(thefuck --alias) # default alias - "fuck"
eval $(thefuck --alias fk) # custom alias - "fk"
# --------------------------------------------------------------------


# ------------------------ zoxide (better cd) ------------------------
eval "$(zoxide init zsh)"
alias cd="z"
# --------------------------------------------------------------------
