#!/bin/bash

# Variables to control various styling options
HIDDEN_THRESHOLD=20
YELLOW_THRESHOLD=50
RED_THRESHOLD=100
SYMBOL=" "

REPO_UPDATES=$(checkupdates | wc -l)

if ! AUR_UPDATES=$( paru -Qu | wc -l ); then
    AUR_UPDATES=0
fi

TOTAL_UPDATES=$(($REPO_UPDATES + $AUR_UPDATES))

# Test line to check the math
# printf 'UPDATES: %s, %s, %s\n' $REPO_UPDATES $AUR_UPDATES $TOTAL_UPDATES

# Use thresholds to determine what class the module should have
if [ $TOTAL_UPDATES -lt $HIDDEN_THRESHOLD ]; then
    STYLE_CLASS=""
    # Change the text elements in order to hide the module - Waybar doesn't
    # support the css display property
    SYMBOL=""
    TOTAL_UPDATES=""
elif [ $TOTAL_UPDATES -ge $YELLOW_THRESHOLD ]; then
    STYLE_CLASS="yellow"
elif [ $TOTAL_UPDATES -ge $RED_THRESHOLD ]; then
    STYLE_CLASS="red"
else
    STYLE_CLASS=""
fi

# Return in JSON format to enable class usage
# TOTAL_UPDATES must be treated as string
# SYMBOL and TOTAL_UPDATES must have quotes to allow empty strings
printf '{"text": "%s%s", "tooltip": "%d repo updates available\r%d AUR updates available", "class": "%s"}' "$SYMBOL" "$TOTAL_UPDATES" $REPO_UPDATES $AUR_UPDATES $STYLE_CLASS
